prog_name: repolite
top_dir: layers  # local directory path for enabled repositories
pull_with_rebase: false  # use --ff-only if false
# add new repo_name sections as needed
repos:
  - repo_name: meta-small-arm-extra
    repo_alias: null
    repo_url: https://github.com/sarnold/meta-small-arm-extra.git
    repo_depth: 0
    repo_remote: origin
    repo_opts: []
    repo_branch: mickledore
    repo_hash: null
    repo_create_tag_msg: tag for test
    repo_create_tag_new: null
    repo_create_tag_annotated: false
    repo_create_tag_signed: false
    repo_push_new_tags: false
    repo_signing_key: null
    repo_changelog_ext: rst
    repo_changelog_base: null
    repo_gen_changes: false
    repo_use_rebase: false
    repo_has_lfs_files: false
    repo_init_submodules: false
    repo_install: false
    repo_enable: true
